TeleService: Switch telephony-ext to a static library
The service cannot really link to the library in runtime and the missing
symbols are preventing successful startups, at least on an emulator
environment with the following trace:

java.lang.NoClassDefFoundError: Failed resolution of: Lorg/codeaurora/internal/IExtTelephony$Stub;
	at com.android.phone.NotificationMgr.<init>(NotificationMgr.java:112)
	at com.android.phone.NotificationMgr.init(NotificationMgr.java:150)
	at com.android.phone.PhoneGlobals.onCreate(PhoneGlobals.java:298)
	at com.android.phone.PhoneApp.onCreate(PhoneApp.java:41)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.codeaurora.internal.IExtTelephony$Stub" on path: DexPathList[[zip file "/system/priv-app/TeleService/TeleService.apk"],nativeLibraryDirectories=[/system/priv-app/TeleService/lib/x86, /system/lib, /vendor/lib, /system/lib, /vendor/lib]]

Change-Id: Ib44eed677db94d14e1ab757b3a7e17c75b2980f6

Conflicts:
	Android.mk